In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [10]:
a=np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [11]:
a[2]

np.int64(3)

In [ ]:
np.arange(3,10)

In [11]:
np.linspace(0,100,9)

array([  0. ,  12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5, 100. ])

In [12]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
n[2,1]

np.int64(8)

In [22]:
n[0,1]=20

In [23]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [24]:
n[2]

array([7, 8, 9])

In [25]:
>>> np.random.rand(5, 2)

array([[0.85528516, 0.01381571],
       [0.44843657, 0.82949242],
       [0.23364091, 0.34468688],
       [0.68866648, 0.26131541],
       [0.30756957, 0.76980101]])

In [27]:
>>> np.random.seed(2)
>>> 100 * np.random.rand(5, 2)


array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [28]:
>>> np.random.seed(2)
>>> np.random.randint(low=0, high=100, size=(5, 2))


array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [29]:
>>> a = np.arange(5)
>>> a

array([0, 1, 2, 3, 4])

In [30]:
a+1

array([1, 2, 3, 4, 5])

In [31]:
a*2

array([0, 2, 4, 6, 8])

In [33]:
b = (10 + (a * 2)) ** 2 / 100

In [34]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [35]:
a+b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [36]:
a>=2

array([False, False,  True,  True,  True])

In [37]:
a[a>b]

array([2, 3, 4])

In [38]:
a


array([0, 1, 2, 3, 4])

In [39]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [3]:
>>> u = np.array([2, 4, 5, 6])

In [4]:
2*u

array([ 4,  8, 10, 12])

In [6]:
v=np.array([1,0,0,2])

In [7]:
u+v

array([3, 4, 5, 8])

In [8]:
u*v

array([ 2,  0,  0, 12])

In [9]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [10]:
vector_vector_multiplication(u, v)



np.float64(14.0)

In [11]:
u.dot(v)

np.int64(14)

In [14]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])


In [16]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [19]:
v

array([1, 0, 0, 2])

In [20]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [21]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [22]:
U.dot(v)

array([14,  5,  5])

In [23]:
>>> V = np.array([
...     [1, 1, 2],
...     [0, 0.5, 1], 
...     [0, 2, 1],
...     [2, 1, 0],
... ])

In [24]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [25]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [26]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [27]:
>>> I = np.eye(3)
>>> I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [29]:
>>> Vs = V[[0, 1, 2]]
>>> Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [30]:
>>> Vs_inv = np.linalg.inv(Vs)
>>> Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [31]:
>>> Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])